### ISSUE TITLE
New Programming languages project 

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hacktoberfest2022#145]
Like mean mern
Go Lang, swing, cloud project

**Comment by RitwikGanguly** [comment]
@prashantkalokhe assign me in this issue, I have 8 to 9 projects to contribute

**Comment by RitwikGanguly** [comment]
@prashantkalokhe 
also I have made a pull request a python project of image visualization
please review and merge that
request number #174

**Comment by prashantkalokhe** [comment]
Add in this one new repo java hactoberfest

**Comment by RitwikGanguly** [comment]
So have I uploade the Java program to this repo or any new repo
Please tell me 

And if in this repo no issues and if any another repo then please give me the link of that
