### ISSUE TITLE
Leet code DSA Questions 

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hacktoberfest2022#146]
Please make your name folder and upload in it

**Comment by srdhal** [comment]
@prashantkalokhe I want to add some of my leetcode questions. Please assign this to me.

**Comment by jainshubham766** [comment]
Hey @prashantkalokhe ,
Please assign it to me too

**Comment by Mohitt0** [comment]
why hacktoberfest exclude my pl

**Comment by SJ-Kumar** [comment]
I would like to add few of my codes. Please assign

**Comment by prashantkalokhe** [comment]
Contribute in new repository java hactoberfest
