### ISSUE TITLE
Hacker rank DSA Codes

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hacktoberfest2022#147]
Please make folders of your name and upload your code in it.
Or make codes in Local system and then upload folder.

It is to understand for other

**Comment by kirtisaraf247** [comment]
Assign it to me sir.

**Comment by jainshubham766** [comment]
Please assign it to me too

**Comment by Git-Akshat01** [comment]
Hi! @jainshubham766 Can you please assign this task to me?

**Comment by jainshubham766** [comment]
create the pr directly under the respective folder 
btw it is excluded from hacktoberfeast

**Comment by sanvi1803** [comment]
> create the pr directly under the respective folder btw it is excluded from hacktoberfeast

Is it??

**Comment by prashantkalokhe** [comment]
New repository made contribute in it
