### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hacktoberfest2022#3]
Add Java programs
Basic to advanced

**Comment by balukalokhe1** [comment]
Assigned to me

**Comment by balukalokhe1** [comment]
//ArrayList class implements the List interface

import java.util.*;  
class TestJavaCollection1{  
public static void main(String args[]){  
ArrayList<String> list=new ArrayList<String>();//Creating arraylist  
list.add("Ravi");//Adding object in arraylist  
list.add("Vijay");  
list.add("Ravi");  
list.add("Ajay");  
//Traversing list through Iterator  
Iterator itr=list.iterator();  
while(itr.hasNext()){  
System.out.println(itr.next());  
}  
}  
}
