### ISSUE TITLE
Add HTML PROJECT 

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hacktoberfest2022#4]
Add any simple complex html css javascript angular js
Project in this issues.

**Comment by balukalokhe1** [comment]
I want to contribute in this

**Comment by kirtisaraf247** [comment]
Kindly describe the issue

**Comment by Nikita0509** [comment]
I want to contribute and add my HTML project

**Comment by prashantkalokhe** [comment]
> Kindly describe the issue

Add your project using html css javascript

**Comment by prashantkalokhe** [comment]
> I want to contribute and add my HTML project

Good upload then make as many congratulations you want

**Comment by siddhesh3607** [comment]
I want to contribute and want to add Html & CSS Inauguration page project  . can you please assign this issue to me

**Comment by prashantkalokhe** [comment]
Make one folder and upload your html project in it

**Comment by suryanshhh28** [comment]
I want to contribute to this project
