### ISSUE TITLE
Update readme.md file 

### ISSUE THREAD

**Issue by prashantkalokhe** [prashantkalokhe/Hacktoberfest2022#5]
Make any enhancement in readme.md file 
Add contribution graph
GitHub snak game 
Any improvement 
In my profile repository also you can make enhancement
Name of that repository is Prashant Kalokhe

**Comment by suryanshhh28** [comment]
please assign me this issue

**Comment by sanvi1803** [comment]
What exactly do we have to update, I'll try to resolve this issue

**Comment by yoharsh14** [comment]
Please assign me this issue

**Comment by kirtisaraf247** [comment]
Assign me the issue please.

**Comment by Ankit-5087** [comment]
Please assign me this issue and also tell what exactly do we need to do.

**Comment by jainshubham766** [comment]
Assign me the issue please.
