### ISSUE TITLE
Majority Element

### ISSUE THREAD

**Issue by hemantsuteri** [prashantkalokhe/Hacktoberfest2022#64]
In an array named nums of size n, we need to return the majority element.

The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

I want to contribute this question to your repository. Please assign this Issue to me with the label of Hacktober fest 2022.
I want to make contributions to Hacktober fest 2022. The issue assigned should be acceptable for Hacktober fest 2022.

**Comment by ankit060801** [comment]
please assign me sir!

**Comment by suryanshhh28** [comment]
please assign me this issue

**Comment by kirtisaraf247** [comment]
Please assign me this issue sir.

**Comment by prashantkalokhe** [comment]
Contribute in new repository java hactoberfest
