### ISSUE TITLE
Valid Parentheses

### ISSUE THREAD

**Issue by hemantsuteri** [prashantkalokhe/Hacktoberfest2022#69]
In a string named s containing just the characters '(', ')', '{', '}', '[' and ']', we have to write a code to determine if the input string is valid.
An input string is valid if:
Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Every close bracket has a corresponding open bracket of the same type.

I want to contribute this question to your repository. Please assign this Issue to me with the label of Hacktober fest 2022.
I want to make contributions to Hacktober fest 2022. The issue assigned should be acceptable for Hacktober fest 2022.

**Comment by kirtisaraf247** [comment]
Kindly describe the issue and assign it to me please.
