### ISSUE TITLE
Missing Number

### ISSUE THREAD

**Issue by hemantsuteri** [prashantkalokhe/Hacktoberfest2022#71]
In a given array named nums containing n distinct numbers in the range [0, n], we have to return the only number in the range that is missing from the array.

I want to contribute this question to your repository. Please assign this Issue to me with the label of Hacktober fest 2022.
I want to make contributions to Hacktober fest 2022. The issue assigned should be acceptable for Hacktober fest 2022.

**Comment by suryanshhh28** [comment]
please assign me this issue

**Comment by kirtisaraf247** [comment]
Assign it to me sir.

**Comment by Shalu461975** [comment]
pleasse assign this to me.it is humble request to you

**Comment by kashish0604** [comment]
Hey @prashantkalokhe please assign this issue to me i can work on it
